plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*.rb'

Minitest/AssertPredicate:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/resque/failure/email_notification.rb'
Rails/PluckId:
  Enabled: true
Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/resque.rake'

Style/ArrayCoercion:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/HashSyntax:
  EnforcedShorthandSyntax: never # TODO: Pending until I get used to 3.1 syntax
Style/RedundantConstantBase:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/StringLiterals:
  Exclude:
    - 'config/importmap.rb'
Style/SymbolArray:
  EnforcedStyle: brackets
